spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/delivery
    username: root
    password: tmdghks10!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#        use_sql_comments: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    defer-datasource-initialization: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
server:
  servlet:
    session:
      timeout: 10080m # 60m * 24h * 7d
      cookie:
        max-age: 10080m
        name: SID
        http-only: true
        secure: true